# Generated by Django 2.1.7 on 2019-07-28 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='comment_num',
            field=models.IntegerField(default=0, verbose_name='评论数'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='fan_num',
            field=models.IntegerField(default=0, verbose_name='粉丝数'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='follow_num',
            field=models.IntegerField(default=0, verbose_name='关注数'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='thumb_num',
            field=models.IntegerField(default=0, verbose_name='点赞数'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='visit_num',
            field=models.IntegerField(default=0, verbose_name='博客访问量'),
        ),
    ]
