# Generated by Django 2.1.7 on 2019-07-28 11:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_title', models.CharField(max_length=40, verbose_name='博客标题')),
                ('blog_text', models.TextField(verbose_name='博客正文')),
                ('category', models.CharField(choices=[('lr', '文学'), ('art', '艺术'), ('emo', '情感'), ('tech', '科技'), ('hth', '健康'), ('bt', '美妆'), ('oth', '其他')], max_length=5, verbose_name='博客分类')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('click_num', models.IntegerField(default=0, verbose_name='点击量')),
                ('thumb_num', models.IntegerField(default=0, verbose_name='点赞数')),
                ('comment_num', models.IntegerField(default=0, verbose_name='评论数')),
                ('addtime', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='博主')),
            ],
            options={
                'verbose_name': '博客信息',
                'verbose_name_plural': '博客信息',
            },
        ),
        migrations.CreateModel(
            name='BookMark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookmark_name', models.CharField(max_length=30, verbose_name='收藏夹名字')),
                ('is_default', models.BooleanField(default=False, verbose_name='是否是默认收藏夹')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('addtime', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='收藏夹拥有者')),
            ],
            options={
                'verbose_name': '收藏夹信息',
                'verbose_name_plural': '收藏夹信息',
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_name', models.CharField(max_length=30, verbose_name='主题内容')),
                ('is_default', models.BooleanField(default=False, verbose_name='是否是默认主题')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('addtime', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='主题拥有者')),
            ],
            options={
                'verbose_name': '主题信息',
                'verbose_name_plural': '主题信息',
            },
        ),
        migrations.AddField(
            model_name='blog',
            name='blog_topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogs.Topic', verbose_name='博客主题'),
        ),
    ]
