# Generated by Django 2.1.7 on 2019-07-28 13:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blogs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCollect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cstatus', models.BooleanField(default=True, verbose_name='是否收藏')),
                ('addtime', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('bookmark', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogs.BookMark', verbose_name='所属收藏夹')),
                ('collect_blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogs.Blog', verbose_name='被收藏博客')),
                ('collector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='收藏者')),
            ],
            options={
                'verbose_name': '收藏信息',
                'verbose_name_plural': '收藏信息',
            },
        ),
        migrations.CreateModel(
            name='UserComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listener_id', models.IntegerField(verbose_name='评论接收者')),
                ('comment_content', models.CharField(max_length=100, verbose_name='评论内容')),
                ('listener_read', models.BooleanField(default=False, verbose_name='评论接收者是否已读')),
                ('author_read', models.BooleanField(default=False, verbose_name='博主是否已读')),
                ('listener_del', models.BooleanField(default=False, verbose_name='评论接收者是否删除')),
                ('author_del', models.BooleanField(default=False, verbose_name='博主是否删除')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('addtime', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('comment_blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogs.Blog', verbose_name='被评论的博客')),
                ('speaker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='评论发出者')),
            ],
            options={
                'verbose_name': '评论信息',
                'verbose_name_plural': '评论信息',
            },
        ),
        migrations.CreateModel(
            name='UserFollow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idol_id', models.IntegerField(verbose_name='偶像的id')),
                ('fstatus', models.BooleanField(default=True, verbose_name='是否关注')),
                ('is_mutual', models.BooleanField(default=False, verbose_name='是否互关')),
                ('is_read', models.BooleanField(default=False, verbose_name='是否已读')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('addtime', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('oneself', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='小粉丝')),
            ],
            options={
                'verbose_name': '关注信息',
                'verbose_name_plural': '关注信息',
            },
        ),
        migrations.CreateModel(
            name='UserNotice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notice_content', models.TextField(verbose_name='通知内容')),
                ('is_read', models.BooleanField(default=False, verbose_name='是否已读')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('addtime', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='被通知人')),
            ],
            options={
                'verbose_name': '系统通知信息',
                'verbose_name_plural': '系统通知信息',
            },
        ),
        migrations.CreateModel(
            name='UserThumbup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tstatus', models.BooleanField(default=True, verbose_name='是否赞')),
                ('is_read', models.BooleanField(default=False, verbose_name='是否已读')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('addtime', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('oneself', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='点赞者')),
                ('thumbup_blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogs.Blog', verbose_name='被赞的博客')),
            ],
            options={
                'verbose_name': '点赞信息',
                'verbose_name_plural': '点赞信息',
            },
        ),
    ]
