"""
Django settings for kkblog project.

Generated by 'django-admin startproject' using Django 2.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""

import os,sys

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
#把extra_apps文件夹的路径也添加进来，这样里面的xadmin就能被识别了
sys.path.insert(0,os.path.join(BASE_DIR,'extra_apps'))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '^9nbpzt*b@b*0$xj@khbt#enz3b#hhgetwebeax)0^y#@*$o(6'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    #下面是自己的app
    'users.apps.UsersConfig',
    'blogs.apps.BlogsConfig',
    'operations.apps.OperationsConfig',
    #下面是第三方app
    'xadmin',
    'crispy_forms',
    'captcha',
]

#别忘了声明用户信息表的继承属性
AUTH_USER_MODEL='users.UserProfile'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'kkblog.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        #配置模板文件夹路径
        'DIRS': [os.path.join(BASE_DIR,'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                #有下面这一句才能在模板里使用{{MEDIA_URL}}
                'django.template.context_processors.media',
            ],
        },
    },
]

WSGI_APPLICATION = 'kkblog.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.1/ref/settings/#databases

#配置数据库
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'kkblog',
        'USER':'root',
        'PASSWORD':'19690607',
        'HOST':'localhost',
        'PORT':'3306',
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.1/topics/i18n/


#下面是汉化部分，需要调整的是Language code Time zone和USE_TZ
LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.1/howto/static-files/

STATIC_URL = '/static/'
#下面是开发阶段对静态文件夹的设置
STATICFILES_DIRS=[
    os.path.join(BASE_DIR,'static'),
]

#下面是对上传的媒体文件的文件夹设置，开发阶段和上线状态是一致的
MEDIA_URL='/static/media/'
MEDIA_ROOT=os.path.join(BASE_DIR,'static/media')

#配置用于发送邮件的邮箱
EMAIL_HOST='smtp.qq.com'
EMAIL_PORT=25
#为了安全，删除了qq邮箱，每天第一件事记得加回来
EMAIL_HOST_USER='2276810913@qq.com'
#我的授权码因为更改邮箱密码所以过期了
EMAIL_HOST_PASSWORD='ehayjedqavfteccf'
EMAIL_USE_TLS=True
EMAIL_FROM='2276810913@qq.com'